<a href="https://colab.research.google.com/github/NguyenDa18/Police-Data-Initiative-Officer-Involved-Shootings-Analysis/blob/master/Portland_Police_Shootings.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd

In [0]:
police_shooting_datasets = {
    'Portland_OR': 'https://public.tableau.com/views/PPBOpenDataDownloads/OIS-All.csv?:showVizHome=no'
}

In [0]:
df = pd.read_csv(police_shooting_datasets['Portland_OR'], parse_dates=['Day of Date Time'])

In [0]:
df.columns

Index(['Any Officer Fatal Injuries?', 'Any Officers Injured on Case?',
       'Case #', 'Day of Date Time', 'Deadly Force Type',
       'Did Subject Fire Shots at Officers?', 'General Location',
       'Grand Jury Transcripts link', 'Initial Call Type',
       'Internal Affairs Investigation Link',
       'Internal Affairs Investigation Link 2 (as needed)', 'Officer Race',
       'Officer Sex', 'Online PDF Link', 'Subject Name', 'Subject Race',
       'Subject Sex', 'Subject Weapon Type (NIBRS)',
       'Was Subject Actually Armed?', 'Was Subject Injured?',
       'Was Subject Injury Fatal?', 'Was Subject Percieved as Armed?',
       'Number of Officers Injured on Case', 'Officer Tenure (yrs)',
       'Subject Age'],
      dtype='object')

In [0]:
h = df[['Day of Date Time', 'Subject Race', 'Was Subject Actually Armed?', 'Was Subject Injured?',
       'Was Subject Injury Fatal?', 'Was Subject Percieved as Armed?','Any Officer Fatal Injuries?', 'Any Officers Injured on Case?',
       'Number of Officers Injured on Case', 'Subject Sex','Officer Race','Officer Sex']]
h.sort_values(by='Day of Date Time')

   Day of Date Time Subject Race  ... Officer Race Officer Sex
0        2010-01-29        Black  ...        White        Male
1        2010-03-22        White  ...        White        Male
47       2010-05-12        Black  ...        White        Male
2        2010-11-23        White  ...        White        Male
3        2010-12-17        White  ...        White        Male
4        2010-12-27        White  ...        White        Male
5        2011-01-01        Black  ...        White        Male
6        2011-01-02        White  ...        White        Male
7        2011-01-02        White  ...        White        Male
49       2011-03-06        White  ...        White        Male
48       2011-03-06        White  ...        White      Female
8        2011-06-30        White  ...        White        Male
9        2012-01-25        White  ...        White        Male
10       2012-03-26        White  ...        White        Male
11       2012-07-17        Black  ...        White        Male
12       2012-07-28        White  ...        White        Male
46       2012-08-21        White  ...        White        Male
13       2012-09-29        White  ...        White        Male
14       2013-02-17        White  ...        White        Male
16       2013-03-04     Hispanic  ...        White        Male
15       2013-03-04     Hispanic  ...        White      Female
50       2014-03-12        White  ...     Hispanic        Male
51       2014-04-16        White  ...        White        Male
17       2014-06-12        White  ...        White        Male
18       2014-09-01        Black  ...        White        Male
43       2015-02-17        White  ...        White        Male
19       2015-03-22        White  ...        Asian        Male
20       2015-05-17        White  ...        White      Female
21       2015-06-28        White  ...     Hispanic        Male
22       2015-06-28        White  ...        White        Male
52       2015-07-05        White  ...        White        Male
23       2015-11-06        White  ...        White        Male
24       2016-05-24        White  ...        White        Male
25       2016-12-05        White  ...        White        Male
26       2017-02-09        Black  ...        White        Male
27       2017-02-09        White  ...        White        Male
28       2017-05-10        Black  ...        White        Male
29       2017-05-28        White  ...        White      Female
30       2017-05-28        White  ...        White        Male
31       2017-08-30        White  ...        White        Male
32       2017-10-25        Black  ...        White        Male
33       2018-03-08        White  ...        White        Male
34       2018-04-07        White  ...        White        Male
35       2018-09-30        Black  ...        White        Male
36       2018-10-10        White  ...        White        Male
53       2018-10-19        White  ...        White        Male
44       2018-12-07        White  ...        White        Male
45       2019-01-02        White  ...        Black        Male
37       2019-01-06        Black  ...        White        Male
39       2019-04-29        White  ...        White        Male
38       2019-04-29        White  ...  Undisclosed        Male
40       2019-06-09        White  ...        White        Male
41       2019-07-30        White  ...        White        Male
42       2019-12-08        White  ...  Undisclosed        Male

[54 rows x 12 columns]

In [19]:
df['Subject Race'].value_counts()

White       42
Black       10
Hispanic     2
Name: Subject Race, dtype: int64